import streamlit as st

st.title("Welcome to our study!")


st.header("What is the purpose of this study?")
st.write(
    """
You are invited to participate in a research study that aims to evaluate certain aspects of AI-generated texts. Before you decide to participate, it is important for you to understand the nature of the study and what will be expected of you. Please read the following information carefully, and feel free to ask any questions before providing your consent.
The purpose of this study is to assess various aspects of AI-generated texts and gather insights into their quality, relevance, and impact.
    """
)
st.divider()
st.subheader("Procedures")
st.write(
    """
    As a participant, you will be presented with short reading texts generated by an AI model or by an human, followed by a series of questions related to the text. Your responses to these questions will be used for research analysis. 
    """
)
st.divider()
st.subheader("Risks and Benefits")
st.write(
    """
    There are no risks associated with this study. The benefits of this study include the possibility of contributing to the research on AI-generated texts.
    """
)
st.divider()
st.subheader("Confidentiality")
st.write(
    """
    Your participation in this study is anonymous. Your responses will be stored and analyzed in an anonymized form. Your responses will be used for research purposes only and will not be shared with any third parties.
    """
)
st.divider()
st.subheader("Voluntary Participation")
st.write(
    """
    Your participation in this study is voluntary. You may refuse to participate or withdraw from the study at any time without penalty or loss of benefits to which you are otherwise entitled. You may refuse to answer any questions that you do not wish to answer and still remain in the study.
    """
)
st.divider()
st.subheader("Contact Information")
st.write(
    """
    If you have any questions about this study, please contact the researchers at: **alp.akova@studenti.unipd.it**
    """
)
st.divider()
st.subheader("Consent")
st.write(
    """
    By clicking on the button below, you confirm that you have read and understood the information provided above and that you agree to participate in this study.
    """
)
if st.button("I agree"):
    st.write("Thank you for your consent please click on the button located on the left to start the study")


